### ISSUE TITLE
have a plan to support the  Shelley  mainnet？

### ISSUE THREAD

**Issue by bocaigo** [input-output-hk/cardano-transactions#29]
When cardano-cli is used to submit a transaction, txID cannot be returned in real time. Is there any method to obtain TXID when submitting a transaction? Or is there any plan to support Shelley main network

**Comment by rvl** [comment]
Hi @bocaigo, the txid is already known before submitting the transaction.

You can see it with the `cardano-cli transaction txid` command.

**Comment by bocaigo** [comment]
hi,This method can solve my problem. plan to deal with it this way. thx




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "input-output-hk/cardano-transactions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 上午10:27
收件人:&nbsp;"input-output-hk/cardano-transactions"<cardano-transactions@noreply.github.com&gt;;
抄送:&nbsp;"~海~"<985433536@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [input-output-hk/cardano-transactions] have a plan to support the  Shelley  mainnet？ (#29)





 
Hi @bocaigo, the txid is already known before submitting the transaction.
 
You can see it with the cardano-cli transaction txid command.

**Comment by bocaigo** [comment]
This method can solve my problem. plan to deal with it this way. thx @rvl
