### ISSUE TITLE
Repo Preparation for MBO

### ISSUE THREAD

**Issue by ThatGuyLLC** [input-output-hk/cardano-transactions#32]
This repo has been marked as core tech and is part of initiative of repo preparation, part of this includes adding needed missing documentation.
This repo in particular needs:

Explain how to make a contribution (Contributing MD)
Include the Standard Code of Conduct
Identify the Core Maintainers

**Comment by coot** [comment]
Done according to [ADAP-2785](https://input-output.atlassian.net/browse/ADP-2785).
